import { createHash } from "node:crypto"
import { readFileSync, readdirSync } from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"

import { onRequestGet, onRequestPost } from "../functions/api/votes.js"
import {
  MODEL_NAME as DEEPSEEK_MODEL_NAME,
  isDeepseekV4FlashShowcaseId,
  showcaseComponents as deepseekComponents,
  showcaseIds as deepseekIds,
} from "@/components/model-showcases/deepseek-v4-flash"
import {
  MODEL_NAME as GLM_53_FLASH_MODEL_NAME,
  isGlm53FlashShowcaseId,
  showcaseComponents as glm53FlashComponents,
  showcaseIds as glm53FlashIds,
} from "@/components/model-showcases/glm-5.3-flash"
import {
  MODEL_NAME as FABLE_MODEL_NAME,
  isFableShowcaseId,
  showcaseComponents as fableComponents,
  showcaseIds as fableIds,
} from "@/components/model-showcases/fable-5.1"
import {
  generateMetadata as generateDeepseekMetadata,
  generateStaticParams as generateDeepseekStaticParams,
} from "@/app/model-showcase/deepseek-v4-flash/[showcaseId]/page"
import {
  generateMetadata as generateGlm53FlashMetadata,
  generateStaticParams as generateGlm53FlashStaticParams,
} from "@/app/model-showcase/glm-5.3-flash/[showcaseId]/page"
import {
  generateMetadata as generateFableMetadata,
  generateStaticParams as generateFableStaticParams,
} from "@/app/model-showcase/fable-5.1/[showcaseId]/page"
import { showcases } from "@/data/showcases"

describe("model release routes", () => {
  it("registers all 18 Fable, GLM, and DeepSeek pages with matching components", () => {
    expect(FABLE_MODEL_NAME).toBe("Fable 5.1")
    expect(GLM_53_FLASH_MODEL_NAME).toBe("GLM 5.3 Flash")
    expect(DEEPSEEK_MODEL_NAME).toBe("DeepSeek V4 flash 0731")
    expect(generateFableStaticParams()).toEqual(
      fableIds.map((showcaseId) => ({ showcaseId }))
    )
    expect(generateGlm53FlashStaticParams()).toEqual(
      glm53FlashIds.map((showcaseId) => ({ showcaseId }))
    )
    expect(generateDeepseekStaticParams()).toEqual(
      deepseekIds.map((showcaseId) => ({ showcaseId }))
    )
    expect(Object.keys(fableComponents)).toEqual(fableIds)
    expect(Object.keys(glm53FlashComponents)).toEqual(glm53FlashIds)
    expect(Object.keys(deepseekComponents)).toEqual(deepseekIds)
    expect(isFableShowcaseId("standard-builder")).toBe(true)
    expect(isFableShowcaseId("unknown")).toBe(false)
    expect(isGlm53FlashShowcaseId("standard-builder")).toBe(true)
    expect(isGlm53FlashShowcaseId("unknown")).toBe(false)
    expect(isDeepseekV4FlashShowcaseId("standard-builder")).toBe(true)
    expect(isDeepseekV4FlashShowcaseId("unknown")).toBe(false)
  })

  it("uses the full release names in page metadata", async () => {
    await expect(
      generateFableMetadata({ params: Promise.resolve({ showcaseId: "standard-builder" }) })
    ).resolves.toEqual({
      title: "Fable 5.1 Standard Builder | Muse Showcase",
      description: "Muse AI Campaign Studio generated by Fable 5.1 with frontend-app-builder.",
      alternates: {
        canonical: "/model-showcase/fable-5.1/standard-builder",
      },
    })
    await expect(
      generateGlm53FlashMetadata({ params: Promise.resolve({ showcaseId: "standard-builder" }) })
    ).resolves.toEqual({
      title: "GLM 5.3 Flash Standard Builder | Muse Showcase",
      description:
        "Muse AI Campaign Studio generated by GLM 5.3 Flash with frontend-app-builder.",
      alternates: {
        canonical: "/model-showcase/glm-5.3-flash/standard-builder",
      },
    })
    await expect(
      generateDeepseekMetadata({
        params: Promise.resolve({ showcaseId: "standard-builder" }),
      })
    ).resolves.toEqual({ title: "DeepSeek V4 flash 0731 Standard Builder | Muse Showcase" })
    await expect(
      generateFableMetadata({ params: Promise.resolve({ showcaseId: "unknown" }) })
    ).resolves.toEqual({ title: "Muse Showcase" })
    await expect(
      generateDeepseekMetadata({ params: Promise.resolve({ showcaseId: "unknown" }) })
    ).resolves.toEqual({ title: "Muse Showcase" })
  })

  it("keeps the full Fable 5.1 name visible in every generated page component", () => {
    const componentDirectory = path.join(
      process.cwd(),
      "src/components/model-showcases/fable-5.1"
    )
    const pageFiles = readdirSync(componentDirectory).filter(
      (fileName) => fileName.endsWith(".tsx") && fileName !== "index.tsx"
    )

    expect(pageFiles).toHaveLength(18)
    pageFiles.forEach((fileName) => {
      expect(readFileSync(path.join(componentDirectory, fileName), "utf8")).toContain("Fable 5.1")
    })
  })

  it("keeps the full DeepSeek name visible in every generated page component", () => {
    const componentDirectory = path.join(
      process.cwd(),
      "src/components/model-showcases/deepseek-v4-flash"
    )
    const pageFiles = readdirSync(componentDirectory).filter(
      (fileName) => fileName.endsWith(".tsx") && fileName !== "index.tsx"
    )

    expect(pageFiles).toHaveLength(18)
    pageFiles.forEach((fileName) => {
      expect(readFileSync(path.join(componentDirectory, fileName), "utf8")).toContain(
        "DeepSeek V4 flash 0731"
      )
    })
  })

  it("keeps the full GLM 5.3 Flash name visible in every migrated page component", () => {
    const componentDirectory = path.join(
      process.cwd(),
      "src/components/model-showcases/glm-5.3-flash"
    )
    const pageFiles = readdirSync(componentDirectory).filter(
      (fileName) => fileName.endsWith(".tsx") && fileName !== "index.tsx"
    )

    expect(pageFiles).toHaveLength(18)
    pageFiles.forEach((fileName) => {
      expect(readFileSync(path.join(componentDirectory, fileName), "utf8")).toContain(
        "GLM 5.3 Flash"
      )
    })
  })
})

describe("model release assets", () => {
  it("uses the actual WebP content hash as the gallery cache version", () => {
    showcases
      .filter(
        (item) =>
          item.model === FABLE_MODEL_NAME ||
          item.model === GLM_53_FLASH_MODEL_NAME ||
          item.model === DEEPSEEK_MODEL_NAME
      )
      .forEach((item) => {
        const [screenshotPath, query] = item.screenshots.desktop.split("?")
        const bytes = readFileSync(
          path.join(process.cwd(), "public", screenshotPath.replace(/^\/+/, ""))
        )
        const digest = createHash("sha256").update(bytes).digest("hex").slice(0, 12)

        expect(query).toBe(`v=${digest}`)
      })
  })
})

function createVotesDb() {
  return {
    prepare(sql: string) {
      return {
        bind(...params: string[]) {
          return {
            async all() {
              if (sql.includes("GROUP BY target_id")) {
                return { results: params.map((targetId) => ({ target_id: targetId, count: 1 })) }
              }
              return { results: [] }
            },
            async first() {
              if (sql.includes("vote_rate_limits")) return null
              if (sql.includes("COUNT(*)")) return { count: 1 }
              return null
            },
            async run() {
              return { success: true }
            },
          }
        },
      }
    },
  }
}

describe("model release voting", () => {
  it("accepts Opus, Fable, GLM, and DeepSeek targets and filters retired or unknown targets", async () => {
    const db = createVotesDb()
    const response = await onRequestGet({
      env: { VOTES_DB: db },
      request: new Request(
        "https://arena.example/api/votes?ids=opus-5.5-standard-builder,fable-5.1-standard-builder,glm-5.3-flash-standard-builder,deepseek-v4-flash-standard-builder,ox-standard-builder,unknown-standard-builder"
      ),
    })

    await expect(response.json()).resolves.toEqual({
      enabled: false,
      counts: {
        "opus-5.5-standard-builder": 1,
        "fable-5.1-standard-builder": 1,
        "glm-5.3-flash-standard-builder": 1,
        "deepseek-v4-flash-standard-builder": 1,
      },
      voted: [],
    })
  })

  it("records valid Fable and DeepSeek votes and rejects the retired Ox model slug", async () => {
    const env = { VOTES_DB: createVotesDb(), VOTE_HASH_SALT: "test-salt" }
    const fableResponse = await onRequestPost({
      env,
      request: new Request("https://arena.example/api/votes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ targetId: "fable-5.1-standard-builder" }),
      }),
    })
    const validResponse = await onRequestPost({
      env,
      request: new Request("https://arena.example/api/votes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ targetId: "deepseek-v4-flash-standard-builder" }),
      }),
    })
    const invalidResponse = await onRequestPost({
      env,
      request: new Request("https://arena.example/api/votes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ targetId: "ox-standard-builder" }),
      }),
    })

    expect(fableResponse.status).toBe(200)
    await expect(fableResponse.json()).resolves.toEqual({
      targetId: "fable-5.1-standard-builder",
      count: 1,
      voted: true,
    })
    expect(validResponse.status).toBe(200)
    await expect(validResponse.json()).resolves.toEqual({
      targetId: "deepseek-v4-flash-standard-builder",
      count: 1,
      voted: true,
    })
    expect(invalidResponse.status).toBe(400)
    await expect(invalidResponse.json()).resolves.toEqual({ error: "Invalid target." })
  })
})
