import { notFound } from "next/navigation"

import {
  MODEL_NAME,
  MODEL_SLUG,
  isFableShowcaseId,
  showcaseComponents,
  showcaseIds,
  showcaseSkills,
  showcaseTitles,
} from "@/components/model-showcases/fable-5.1"

export const dynamicParams = false

export function generateStaticParams() {
  return showcaseIds.map((showcaseId) => ({ showcaseId }))
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ showcaseId: string }>
}) {
  const { showcaseId } = await params

  if (isFableShowcaseId(showcaseId)) {
    return {
      title: `${MODEL_NAME} ${showcaseTitles[showcaseId]} | Muse Showcase`,
      description: `Muse AI Campaign Studio generated by ${MODEL_NAME} with ${showcaseSkills[showcaseId]}.`,
      alternates: {
        canonical: `/model-showcase/${MODEL_SLUG}/${showcaseId}`,
      },
    }
  }

  return {
    title: "Muse Showcase",
  }
}

export default async function Page({
  params,
}: {
  params: Promise<{ showcaseId: string }>
}) {
  const { showcaseId } = await params

  if (!isFableShowcaseId(showcaseId)) {
    notFound()
  }

  const Showcase = showcaseComponents[showcaseId]
  return <Showcase />
}
