import type { ArenaLocale } from "@/lib/arena-gallery"
const copy = {
  "zh-CN": {
    works: "作品", skills: "Skills", method: "项目简报", contribute: "贡献作品",
    menu: "导航菜单", close: "关闭", skip: "跳至主要内容", github: "GitHub 项目",
    authorSite: "个人站", language: "界面语言", promptAction: "复制提示词", copyContribution: "复制提示词",
     headline: ["同一个需求，", "看见设计的不同。"],
    brief: "共同任务", briefName: "Muse · AI Campaign Studio",
    modelsCount: "个模型", chainsCount: "种组合", worksCount: "件作品", collection: "作品集",
    controlled: "共同条件", search: "搜索作品", searchHint: "模型、技能或设计重点…",
    model: "模型", chain: "技能组合", allModels: "全部模型", allChains: "全部组合", filters: "筛选", clear: "清空",
      results: "件作品", noResults: "没有找到这样的作品", noResultsHint: "换一个关键词，或清空筛选继续探索。",
    next: "下一页", previous: "上一页", page: "页",
    viewWork: "查看作品",
    designGoal: "设计目标",  openWork: "打开交互作品", copyPrompt: "复制提示词", copyContext: "复制本组合上下文", copied: "已复制",
    copyFailed: "复制失败，请选中文本手动复制。", share: "复制分享链接", desktop: "桌面大图", mobile: "手机效果",
    desktopCapture: "桌面首屏截图", mobileCapture: "手机截图", zoom: "原尺寸观察", fit: "适合窗口", retry: "重新加载",
    imageError: "截图暂时无法加载", imageErrorHint: "仍可打开独立页面查看作品。", loading: "正在加载作品…",
    previewError: "预览未能完成加载", previewErrorHint: "可以重试，或直接打开交互作品。", mobileLive: "实时手机布局",

    metadata: "生成记录", unknown: "未记录",
    generatedAt: "生成日期", modelVersion: "模型名称", skillVersion: "生成时技能版本", previewLabel: "作品详情",
    shareRepair: "链接中的部分条件已失效，已保留可用内容。", dismiss: "知道了", likesUnavailable: "喜欢暂不可用",
    like: "喜欢", liked: "已喜欢", readBrief: "查看需求与边界", promptTitle: "本组合生成上下文", showPrompt: "查看完整上下文",
    footer: "Design Skill Arena", footerNote: "Muse · AI Campaign Studio",
     skillsTitle: "Skills",
    searchSkills: "搜索技能", skillSearchHint: "技能名称或用途…", allTypes: "全部类型", skillType: "类型",
     combinations: "关联组合", official: "官方说明", repository: "来源仓库",
    sourceRevision: "来源修订", notRecorded: "未记录固定版本",  historical: "历史版本",
    noSkills: "没有找到相关技能",  skillPage: "技能资料", versionNote: "作品生成时的技能版本未记录。",
     methodTitle: "Muse · AI Campaign Studio",
    taskTitle: "新品发布，三种创意方向。", taskBody: "服务对象：创意总监。交付内容：新品发布活动方案。",
    requirementsTitle: "任务范围", requirements: ["活动简报 · 受众、渠道、语气与视觉风格", "创意提案 · A / B / C 三个方向", "效果预测 · Reach / CTR / Conversion（模拟数据）", "活动管理 · 生成、保存与导出", "完整交互状态"],
    fixedTitle: "保持一致", fixed: ["Muse 产品任务与核心功能要求", "独立可打开的页面", "通过本地 mock 数据展示交互"],
    variedTitle: "允许变化", varied: ["模型与设计技能组合", "布局、视觉表达、文案与主题素材", "组件组织、响应式与交互实现"],
    limitsTitle: "作品记录", limitsBody: "单一任务的独立作品样本，无统一评分。",
    contributionTitle: "贡献作品", contributionBody: "一个模型，18 种组合。",
    contributionPrompt: "查看贡献提示词", contributingGuide: "阅读贡献指南", contributionDialog: "贡献作品提示词",
  },
  "en-US": {
    works: "Collection", skills: "Skills", method: "Brief", contribute: "Contribute",
    menu: "Navigation menu", close: "Close", skip: "Skip to content", github: "GitHub project",
    authorSite: "Personal site", language: "Interface language", promptAction: "Copy prompt", copyContribution: "Copy prompt",
     headline: ["One shared brief.", "A world of different design."],
    brief: "THE SHARED BRIEF", briefName: "Muse · AI Campaign Studio",
    modelsCount: "models", chainsCount: "chains", worksCount: "works", collection: "The collection",
    controlled: "Shared conditions", search: "Search works", searchHint: "Model, skill, or design focus…",
    model: "Model", chain: "Skill chain", allModels: "All models", allChains: "All chains", filters: "Filters", clear: "Clear",
      results: "works", noResults: "No works found", noResultsHint: "Try another keyword or clear the filters to keep exploring.",
    next: "Next", previous: "Previous", page: "Page",
    viewWork: "View work",
    designGoal: "Design intent",  openWork: "Open interactive work", copyPrompt: "Copy prompt", copyContext: "Copy chain context", copied: "Copied",
    copyFailed: "Could not copy. Select the text to copy it manually.", share: "Copy share link", desktop: "Desktop image", mobile: "Mobile view",
    desktopCapture: "Desktop viewport capture", mobileCapture: "Mobile capture", zoom: "Actual size", fit: "Fit to view", retry: "Try again",
    imageError: "This image could not load", imageErrorHint: "You can still open the standalone work.", loading: "Loading the work…",
    previewError: "The preview could not finish loading", previewErrorHint: "Try again or open the interactive work directly.", mobileLive: "Live mobile layout",

    metadata: "Generation record", unknown: "Not recorded",
    generatedAt: "Generated on", modelVersion: "Model name", skillVersion: "Skills at generation", previewLabel: "Work details",
    shareRepair: "Some linked conditions are no longer available. The valid content is still shown.", dismiss: "Dismiss", likesUnavailable: "Likes unavailable",
    like: "Like", liked: "Liked", readBrief: "Read the brief & boundaries", promptTitle: "Context for this chain", showPrompt: "Read the full context",
    footer: "Design Skill Arena", footerNote: "Muse · AI Campaign Studio",
     skillsTitle: "Skills",
    searchSkills: "Search skills", skillSearchHint: "Skill name or purpose…", allTypes: "All types", skillType: "Type",
     combinations: "Related chains", official: "Official docs", repository: "Source repository",
    sourceRevision: "Source revision", notRecorded: "No pinned version recorded",  historical: "Historical version",
    noSkills: "No matching skills",  skillPage: "Skill reference", versionNote: "Skill versions at generation are not recorded.",
     methodTitle: "Muse · AI Campaign Studio",
    taskTitle: "One launch. Three creative directions.", taskBody: "Audience: creative directors. Deliverable: a product launch campaign.",
    requirementsTitle: "Scope", requirements: ["Campaign brief · audience, channels, tone, and visual style", "Creative proposals · directions A / B / C", "Forecasts · Reach / CTR / Conversion (simulated)", "Campaign management · generate, save, and export", "Complete interaction states"],
    fixedTitle: "Shared conditions", fixed: ["The Muse product brief and core requirements", "Independently accessible pages", "Local mock data for interactions"],
    variedTitle: "Independent decisions", varied: ["Models and design skill chains", "Layout, visual direction, copy, and thematic imagery", "Component structure, responsiveness, and interactions"],
    limitsTitle: "Records and limitations", limitsBody: "Independent samples from a single brief. No standardized scores.",
    contributionTitle: "Contribute works", contributionBody: "One model. Eighteen chains.",
    contributionPrompt: "View contribution prompt", contributingGuide: "Read the contribution guide", contributionDialog: "Contribution prompt",
  },
} as const
export function arenaCopy(locale: ArenaLocale) { return copy[locale] }
