import { notFound } from "next/navigation"

import {
  MODEL_NAME,
  MODEL_SLUG,
  isDeepseekV41FlashShowcaseId,
  showcaseComponents,
  showcaseIds,
  showcaseSkills,
  showcaseTitles,
} from "@/components/model-showcases/deepseek-v4.1-flash"

export const dynamicParams = false

export function generateStaticParams() {
  return showcaseIds.map((showcaseId) => ({
    showcaseId,
  }))
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ showcaseId: string }>
}) {
  const { showcaseId } = await params

  if (isDeepseekV41FlashShowcaseId(showcaseId)) {
    return {
      title: `${MODEL_NAME} ${showcaseTitles[showcaseId]} | Muse Showcase`,
      description: `Muse AI Campaign Studio generated by ${MODEL_NAME} with ${showcaseSkills[showcaseId]}.`,
      alternates: {
        canonical: `/model-showcase/${MODEL_SLUG}/${showcaseId}`,
      },
    }
  }

  return {
    title: "Muse Showcase",
  }
}

export default async function Page({
  params,
}: {
  params: Promise<{ showcaseId: string }>
}) {
  const { showcaseId } = await params

  if (isDeepseekV41FlashShowcaseId(showcaseId)) {
    const Showcase = showcaseComponents[showcaseId]
    return <Showcase />
  }

  notFound()
}
